// Renders .env.example as a markdown key table. Keys and comments only: no example values.
export function renderEnvMarkdown(exampleText) {
  const rows = [];
  let comments = [];
  for (const line of exampleText.split(/\r?\n/)) {
    if (line.startsWith("#")) {
      comments.push(line.slice(1).trim());
      continue;
    }
    const key = /^([A-Z][A-Z0-9_]*)=/.exec(line)?.[1];
    if (key) rows.push({ key, comment: comments.join(" ") });
    comments = [];
  }
  const escapePipes = (text) => text.replaceAll("|", "\\|");
  return [
    "# Environment variables",
    "",
    "Generated by `npm run check:env -- --markdown` from `.env.example`. Do not edit by hand.",
    "",
    "| Key | Description |",
    "| --- | --- |",
    ...rows.map(({ key, comment }) => `| \`${key}\` | ${escapePipes(comment)} |`),
    "",
  ].join("\n");
}
